CREATE TABLE IF NOT EXISTS docs(col TEXT NOT NULL,id TEXT NOT NULL,data TEXT,updated INTEGER NOT NULL,by TEXT,deleted INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(col,id));
CREATE INDEX IF NOT EXISTS docs_updated ON docs(col,updated);
CREATE TABLE IF NOT EXISTS people(email TEXT PRIMARY KEY,name TEXT,role TEXT NOT NULL DEFAULT 'member',first_seen INTEGER);
CREATE TABLE IF NOT EXISTS blobs(id TEXT PRIMARY KEY,type TEXT,data TEXT NOT NULL,created INTEGER,by TEXT);
